spring:
  profiles:
    active: test
  application:
    name: web-api
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
log:
  path: /logs/web-api


mybatis-plus:
  mapper-locations: classpath:/mapper/*/*Mapper.xml
  # \u5B9E\u4F53\u626B\u63CF\uFF0C\u591A\u4E2Apackage\u7528\u9017\u53F7\u6216\u8005\u5206\u53F7\u5206\u9694
  typeAliasesPackage: com.lg.entity.*
  # \u5168\u5C40\u914D\u7F6E
  global-config:
    # \u6570\u636E\u5E93\u76F8\u5173\u914D\u7F6E
    db-config:
      #\u4E3B\u952E\u7C7B\u578B  AUTO:"\u6570\u636E\u5E93ID\u81EA\u589E", INPUT:"\u7528\u6237\u8F93\u5165ID",ID_WORKER:"\u5168\u5C40\u552F\u4E00ID (\u6570\u5B57\u7C7B\u578B\u552F\u4E00ID)", UUID:"\u5168\u5C40\u552F\u4E00ID UUID";
      id-type: AUTO
      #\u5B57\u6BB5\u7B56\u7565 IGNORED:"\u5FFD\u7565\u5224\u65AD",NOT_NULL:"\u975E NULL \u5224\u65AD"),NOT_EMPTY:"\u975E\u7A7A\u5224\u65AD"
      field-strategy: NOT_NULL
      #\u903B\u8F91\u5220\u9664\u914D\u7F6E
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    #\u914D\u7F6E\u8FD4\u56DE\u6570\u636E\u5E93(column\u4E0B\u5212\u7EBF\u547D\u540D&&\u8FD4\u56DEjava\u5B9E\u4F53\u662F\u9A7C\u5CF0\u547D\u540D)\uFF0C\u81EA\u52A8\u5339\u914D\u65E0\u9700as\uFF08\u6CA1\u5F00\u542F\u8FD9\u4E2A\uFF0CSQL\u9700\u8981\u5199as\uFF1A select user_id as userId\uFF09
    map-underscore-to-camel-case: true
    cache-enabled: false
