spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-8vbaw0t3alyo0v868.mysql.zhangbei.rds.aliyuncs.com:3306/paper-muster?autoReconnect=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false&allowMultiQueries=true
    username: zbh
    password: Fk8@Y0c$TAetaXTu
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  #redis配置
  redis:
    host: r-8vb0y5tdorgc436qun.redis.zhangbei.rds.aliyuncs.com
    port: 6379
    database: 7
    timeout: 30000
    lettuce.pool.min-idle: 0
    lettuce.pool.max-idle: 8
    lettuce.pool.max-active: 8
    lettuce.pool.max-wait: -1ms

server:
  port: 8081

JwtTokenUtil:
  jwtKey: yKBD1EhUDiHgz0Oz

