spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.101.213.249:3306/letter_guarantee?autoReconnect=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false&allowMultiQueries=true
    username: root
    password: zbh1234mysql
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  #redis配置
  redis:
    host: 39.101.213.249
    port: 6379
    database: 7
    timeout: 30000
    lettuce.pool.min-idle: 0
    lettuce.pool.max-idle: 8
    lettuce.pool.max-active: 8
    lettuce.pool.max-wait: -1ms

server:
  port: 8089

JwtTokenUtil:
  jwtKey: safdsafdsafdsafd
